version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200" 
    volumes:
      - ./src:/app/src 
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge
